In [157]:
import pandas as pd
import datetime
import time

df = pd.read_excel('despesas.xlsx')
df2 = pd.read_excel('orcamentos.xlsx')

In [158]:
# Converte a data - despesas
df['Data'] = pd.to_datetime(df['Data'], unit='ms')
df['Data'] = df['Data'].dt.strftime('%d/%m/%Y')
display(df)

,Id_despesa,Data,Tipo,Setor,Valor,Fornecedor
0,1,18/08/2024,Salário,Financeiro,11670.10,Teixeira
1,2,15/09/2024,Água,Logística,17394.82,Nunes
2,3,22/08/2024,Água,Financeiro,19787.46,Moura S/A
3,4,02/09/2024,Compra Matéria-prima,Produção,2159.77,Barros
4,5,02/02/2025,Internet,RH,7390.20,Mendes - EI
...,...,...,...,...,...,...
195,196,03/10/2024,Energia,Produção,15225.10,da Cunha Mendes e Filhos
196,197,19/07/2024,Salário,RH,16460.68,Pires e Filhos
197,198,27/10/2024,Água,Financeiro,12795.28,Nascimento
198,199,17/08/2024,Compra Matéria-prima,Logística,9634.17,da Costa
199,200,10/03/2025,Salário,Produção,13022.00,Porto - ME

In [159]:
# Apaga as linhas com valores vazios - despesas
df = df.dropna()
display(df)

,Id_despesa,Data,Tipo,Setor,Valor,Fornecedor
0,1,18/08/2024,Salário,Financeiro,11670.10,Teixeira
1,2,15/09/2024,Água,Logística,17394.82,Nunes
2,3,22/08/2024,Água,Financeiro,19787.46,Moura S/A
3,4,02/09/2024,Compra Matéria-prima,Produção,2159.77,Barros
4,5,02/02/2025,Internet,RH,7390.20,Mendes - EI
...,...,...,...,...,...,...
195,196,03/10/2024,Energia,Produção,15225.10,da Cunha Mendes e Filhos
196,197,19/07/2024,Salário,RH,16460.68,Pires e Filhos
197,198,27/10/2024,Água,Financeiro,12795.28,Nascimento
198,199,17/08/2024,Compra Matéria-prima,Logística,9634.17,da Costa
199,200,10/03/2025,Salário,Produção,13022.00,Porto - ME

In [160]:
# Formatar a coluna Valor - despesas
df['Valor'] = df['Valor'].astype(float)
display(df)

df.to_excel('despesas-Tratado.xlsx', index=False)

,Id_despesa,Data,Tipo,Setor,Valor,Fornecedor
0,1,18/08/2024,Salário,Financeiro,11670.10,Teixeira
1,2,15/09/2024,Água,Logística,17394.82,Nunes
2,3,22/08/2024,Água,Financeiro,19787.46,Moura S/A
3,4,02/09/2024,Compra Matéria-prima,Produção,2159.77,Barros
4,5,02/02/2025,Internet,RH,7390.20,Mendes - EI
...,...,...,...,...,...,...
195,196,03/10/2024,Energia,Produção,15225.10,da Cunha Mendes e Filhos
196,197,19/07/2024,Salário,RH,16460.68,Pires e Filhos
197,198,27/10/2024,Água,Financeiro,12795.28,Nascimento
198,199,17/08/2024,Compra Matéria-prima,Logística,9634.17,da Costa
199,200,10/03/2025,Salário,Produção,13022.00,Porto - ME

In [161]:
# Formatar os valores - orcamentos
df2['Valor_previsto'] =  df2['Valor_previsto'].astype(float).round(2)
df2['Valor_realizado'] = df2['Valor_realizado'].astype(float).round(2)

display(df2)

         Setor  Mes   Ano  Valor_previsto  Valor_realizado
0     Produção    1  2024        14045.42         15524.52
1     Produção    2  2024        42597.50         45075.42
2     Produção    3  2024        39491.52         44155.59
3     Produção    4  2024        52992.06         59965.36
4     Produção    5  2024        16198.93         15988.45
..         ...  ...   ...             ...              ...
115  Comercial    8  2025        73532.49         63496.66
116  Comercial    9  2025        46526.55        270703.31
117  Comercial   10  2025        42068.07         43491.56
118  Comercial   11  2025        79706.26         92876.93
119  Comercial   12  2025         5122.75          5623.75

[120 rows x 5 columns]

In [162]:
# Mescla e formata as colunas mes e ano - orcamentos
df2['Mes'] = df2['Mes'].astype(str).str.zfill(2)
df2['Ano'] = df2['Ano'].astype(str)
df2['Data'] = pd.to_datetime(df2['Mes'] + '/' + df2['Ano'], format='%m/%Y')
df2['Data'] = df2['Data'].dt.strftime('%m/%y')
display(df2)

df2.to_excel('orcamentos-Tratado.xlsx', index=False)

         Setor Mes   Ano  Valor_previsto  Valor_realizado   Data
0     Produção  01  2024        14045.42         15524.52  01/24
1     Produção  02  2024        42597.50         45075.42  02/24
2     Produção  03  2024        39491.52         44155.59  03/24
3     Produção  04  2024        52992.06         59965.36  04/24
4     Produção  05  2024        16198.93         15988.45  05/24
..         ...  ..   ...             ...              ...    ...
115  Comercial  08  2025        73532.49         63496.66  08/25
116  Comercial  09  2025        46526.55        270703.31  09/25
117  Comercial  10  2025        42068.07         43491.56  10/25
118  Comercial  11  2025        79706.26         92876.93  11/25
119  Comercial  12  2025         5122.75          5623.75  12/25

[120 rows x 6 columns]

In [163]:
# Contabiliza células vazias
vazio = df2.isnull().sum()

print(vazio)

Setor              0
Mes                0
Ano                0
Valor_previsto     0
Valor_realizado    0
Data               0
dtype: int64